/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Antonio
 */
public class InicioActividad extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public InicioActividad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Actividad1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(920, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Bienvenido");

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Seccion 1");

        Actividad1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Actividad1.setForeground(new java.awt.Color(102, 102, 102));
        Actividad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pikachu_72.png"))); // NOI18N
        Actividad1.setText("Level 1");
        Actividad1.setBorder(null);
        Actividad1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Actividad1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pikachu_72.png"))); // NOI18N
        Actividad1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pikachu_96.png"))); // NOI18N
        Actividad1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Actividad1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Actividad1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Actividad1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Title))
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Actividad1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Title)
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Actividad1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 590));
    }// </editor-fold>//GEN-END:initComponents

    private void Actividad1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Actividad1MousePressed
        
    }//GEN-LAST:event_Actividad1MousePressed

    private void Actividad1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Actividad1MouseClicked
        Actividad1 p1= new Actividad1();
        p1.setSize(920, 585);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_Actividad1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actividad1;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
